Delete Database1_log.ldf
test, because couldn't  commit from vs.
Error: 

Git failed with a fatal error.
Git failed with a fatal error.
error: open("OW21BB_HFT_2021221.Data/HospitalDatabase.mdf"): Permission denied
fatal: Unable to process path OW21BB_HFT_2021221.Data/HospitalDatabase.mdf